# Use the official Node.js image as a base
FROM node:22-alpine

# Install Git - we need it because of FE version hash
RUN apk update && apk add --no-cache git

# Set the working directory in the container
WORKDIR /app

# Copy package*.json
COPY package*.json .

# Install dependencies
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN yarn install --modules-folder /node_modules

# Build the Vue.js application
CMD ["yarn", "serve:lcp"]
