# Use the official Node.js image as a base
FROM node:22-alpine as build

# Install Git - we need it because of FE version hash
RUN apk update && apk add --no-cache git

# Set the working directory in the container
WORKDIR /app

# Copy package*.json
# COPY package*.json /app/

# Install dependencies
RUN yarn

# Copy the rest of the application code
# COPY . ./

# Build the Vue.js application
CMD ["yarn", "serve:catchphrase"]
