import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowDown,
  faArrowUp,
  faBackward,
  faBackwardStep,
  faBarcode,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCertificate,
  faChartSimple,
  faCircleInfo,
  faCircleNodes,
  faCirclePlus,
  faCircleQuestion,
  faCopy,
  faDatabase,
  faExpand,
  faFileExport,
  faFont,
  faForward,
  faGear,
  faGlobe,
  faHouse,
  faLink,
  faMagnifyingGlass,
  faMagnifyingGlassChart,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMusic,
  faPause,
  faPlay,
  faPlus,
  faPowerOff,
  faTable,
  faTrash,
  faUser,
  faUserGear,
  faUsers,
  faVideo,
  faVolumeDown,
  faVolumeHigh,
  faVolumeLow,
  faVolumeOff,
  faVolumeUp,
  faVolumeXmark,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

library.add(faArrowDown);
library.add(faArrowUp);
library.add(faBackward);
library.add(faBackwardStep);
library.add(faBarcode);
library.add(faCaretDown);
library.add(faCaretLeft);
library.add(faCaretRight);
library.add(faChartSimple);
library.add(faCertificate);
library.add(faCircleInfo);
library.add(faCircleNodes);
library.add(faCirclePlus);
library.add(faCircleQuestion);
library.add(faCopy);
library.add(faDatabase);
library.add(faExpand);
library.add(faFileExport);
library.add(faFont);
library.add(faForward);
library.add(faGear);
library.add(faGlobe);
library.add(faHouse);
library.add(faLink);
library.add(faMagnifyingGlass);
library.add(faMagnifyingGlassChart);
library.add(faMagnifyingGlassMinus);
library.add(faMagnifyingGlassPlus);
library.add(faMusic);
library.add(faPause);
library.add(faPlay);
library.add(faPlus);
library.add(faPowerOff);
library.add(faTable);
library.add(faTrash);
library.add(faUser);
library.add(faUserGear);
library.add(faUsers);
library.add(faVideo);
library.add(faVolumeDown);
library.add(faVolumeLow);
library.add(faVolumeHigh);
library.add(faVolumeOff);
library.add(faVolumeUp);
library.add(faVolumeXmark);
library.add(faXmark);

export default FontAwesomeIcon;
