#!/bin/bash
#
# Update a superproject when a commit is made to a submodule.

while read variable; do
    unset $variable
done < <(env | grep "^GIT_" | sed 's/=.*//g')

MODULE=${PWD##*/}
GIT="git"
COMMIT_MSG="update $MODULE: `$GIT log -1 --pretty=%B | xargs`"
SUPERPROJECT_WORKING_TREE=`git rev-parse --show-superproject-working-tree`
echo "Committing to $SUPERPROJECT_WORKING_TREE ..."
cd $SUPERPROJECT_WORKING_TREE
$GIT reset
$GIT add "$MODULE"
$GIT commit -m "$COMMIT_MSG"
